Repository Plick-pop-in/poppin-be, pull requests merged in 2024-06, with the labels that each got.

#49 Feat/#5 Map 지도 필터링 구현
  src/main/java/com/soongsil/poppin/popup/application/PopupSearchService.java
  src/main/java/com/soongsil/poppin/popup/application/response/MapPopup.java
  src/main/java/com/soongsil/poppin/popup/domain/PopupRepository.java
  src/main/java/com/soongsil/poppin/popup/presentation/PopupController.java
Labels: pr, feat

#51 [Feat/#47] 결제 API 연결 완료
  src/main/java/com/soongsil/poppin/heart/application/HeartService.java
  src/main/java/com/soongsil/poppin/heart/domain/HeartRepository.java
  src/main/java/com/soongsil/poppin/popup/domain/Popup.java
  src/main/java/com/soongsil/poppin/user/domain/UserRepository.java
  src/main/java/com/soongsil/poppin/userchat/application/UserChatSearchService.java
  src/main/java/com/soongsil/poppin/userchat/application/response/JoinUserChat.java
  src/main/java/com/soongsil/poppin/userchat/domain/UserChat.java
  src/main/java/com/soongsil/poppin/userchat/domain/UserChatRepository.java
  src/main/java/com/soongsil/poppin/userchat/presentation/UserChatController.java
Labels: pr

#62 fix: live response 수정 후 오류 개선
  src/main/java/com/soongsil/poppin/popup/application/PopupSearchService.java
Labels: pr, fix
